In [1]:
import torch

In [3]:
x = torch.empty(3,5)
x

tensor([[8.9082e-39, 9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39, 9.2755e-39],
        [9.7346e-39, 1.0745e-38, 1.0102e-38, 9.9184e-39, 1.0102e-38]])

In [2]:
y = torch.rand(5,)
y 

tensor([0.5623, 0.0446, 0.9330, 0.6947, 0.7310])

In [3]:
z = torch.zeros(5,3, dtype=torch.long)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
aa = list(range(0,10))
aa

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
bb = torch.tensor(aa)
bb

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
aa = torch.arange(1,10,1)
aa

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x = torch.ones(5,3)
x.shape

torch.Size([5, 3])

In [27]:
y = x.clone().view(-1,3)
y.shape

torch.Size([5, 3])

In [28]:
y += 1
y

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [29]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
x = torch.randn(1)
x.shape

torch.Size([1])

In [37]:
print(torch.cuda.is_available())
print(torch.device('cuda'))

True
cuda


In [33]:
y = x.item()
y

0.9750177264213562

In [41]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [43]:
y = x + 1
print(y)
print(id(y))
print(y.grad_fn)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
2042158392728


In [47]:
print(x.is_leaf,y.is_leaf)

True False


In [48]:
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [55]:
z = y**2 *3
out = z.mean()
out

tensor(12., grad_fn=<MeanBackward0>)

In [58]:
a = torch.rand(2,2)
a = ((a *3) / (a - 1))
print(a.requires_grad)

False


In [60]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [62]:
b = (a**2).sum()
print(b.requires_grad)

True


In [63]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [68]:
out.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

In [69]:
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


In [72]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5., 5.],
        [5., 5.]])


In [77]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0],requires_grad=True)
y = 2*x
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [78]:
v = torch.tensor([[1,0.1],[0.01,0.001]], dtype = torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [79]:
v

tensor([[1.0000, 0.1000],
        [0.0100, 0.0010]])

In [ ]:
x = torch.tensor(1.0, requires_grad=True)
y = x**2

with torch.no_grad():
    y2 = x**3
y3 = y1 + y2

